// All course content is generated by tools/ (parse_course.py, gen_options.py, gen_audio.py).
import lexicon from '../../content/lexicon.json';
import options from '../../content/options.json';
import gpc from '../../content/gpc.json';
import ui from '../../content/ui_lines.json';
import audioIndex from '../../content/audio_index.json';
import L102 from '../../content/lessons/L1.02.json';
import L103 from '../../content/lessons/L1.03.json';
import L104 from '../../content/lessons/L1.04.json';
import L105 from '../../content/lessons/L1.05.json';
import L106 from '../../content/lessons/L1.06.json';
import L107 from '../../content/lessons/L1.07.json';
import L108 from '../../content/lessons/L1.08.json';
import L109 from '../../content/lessons/L1.09.json';
import L110 from '../../content/lessons/L1.10.json';
import L111 from '../../content/lessons/L1.11.json';
import L112 from '../../content/lessons/L1.12.json';
import { fillL1 } from './level1.js';

// Level 1: every lesson is playable (single-sitting lessons get their sittings from level1.js).
export const LESSONS = [L102, L103, L104, L105, L106, L107, L108, L109, L110, L111, L112].map(fillL1);
export const lessonById = id => LESSONS.find(l => l.id === id);
export { lexicon, options, gpc, ui, audioIndex };

export const entry = w => lexicon[w] || lexicon[w.toLowerCase()];
export const g2p = Object.fromEntries(gpc.order.map(o => [o.g, o.p]));
export const isHeart = w => entry(w)?.kind === 'heart';

// Sittings for a track. Track A follows the course one sound per sitting; Track B merges the teaching sittings.
export function sittingsFor(lesson, track) {
  return (lesson.appSittings?.[track] || []).map(s => ({ ...s, lessonId: lesson.id, key: `${lesson.id}:${track}:${s.id}` }));
}

// Words a learner can decode by the end of a sitting: real words from the course whose graphemes are all taught.
export function taughtGraphemes(lessonId, sittingId, track) {
  const out = new Set();
  for (const l of LESSONS) {
    for (const s of l.sittings || []) {
      (s.new || []).forEach(g => out.add(g));
      if (l.id === lessonId && track === 'A' && s.id === sittingId) return out;
    }
    if (l.id === lessonId) return out;
  }
  return out;
}

export function blendItems(lesson, sitting) {
  const src = lesson.sittings.find(s => s.id === sitting.id);
  const b = src?.blend || {};
  if (b.syllable) return [{ w: b.syllable, kind: 'syllable' }];
  let real = b.real || [], pseudo = b.pseudo || [];
  if (!real.length && !pseudo.length) { real = lesson.blendList?.real || []; pseudo = lesson.blendList?.pseudo || []; }
  // keep sittings short: up to 3 real + 2 made-up, interleaved
  const r = real.filter(w => options[w.toLowerCase()]).slice(0, 3), p = pseudo.filter(w => options[w.toLowerCase()]).slice(0, 2);
  const out = [];
  for (let i = 0; i < Math.max(r.length, p.length); i++) { if (r[i]) out.push({ w: r[i], kind: 'real' }); if (p[i]) out.push({ w: p[i], kind: 'pseudo' }); }
  return out;
}

export function spellWords(lesson, sitting) {
  const src = lesson.sittings.find(s => s.id === sitting.id);
  const ws = (src?.spell?.words || []).filter(w => entry(w) && entry(w).kind !== 'syllable');
  if (ws.length) return ws.slice(0, 2);
  if (sitting.new?.length) return [];
  return (lesson.check?.dictation || []).slice(0, 1);
}
