#!/usr/bin/env python3
"""Round 3 blind test: Tilo composited INTO 5 different real Sound Out lesson screens vs 5 different Duolingo ABC lesson screens (marketing header and phone frame cropped away).
  python3 tools/build_round3.py  -> design/character/round3/p<N>_<A|B>.png, round3_key.json, round3_key.js
Fix over round 2: the key is derived from the files actually written. Each p<N>_<side>.png is reloaded and compared pixel-for-pixel with the image it
is supposed to hold; the build aborts if any file does not match, so the key cannot disagree with the images."""
import json, os, random, sys, hashlib
from PIL import Image, ImageChops
R = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
sys.path.insert(0, f"{R}/tools")
from gen_tilo import to_alpha
C = f"{R}/design/character"; O = f"{C}/round3"; os.makedirs(O, exist_ok=True)
W, H = 420, 608
# the five lesson screens are frozen copies of app/shots (that folder is regenerated by the level driver) in round3/screens/
# (Sound Out screen, Tilo pose, crop top y, width as fraction of 780, x centre fraction, y bottom in crop) vs (Duolingo shot n, crop box in 392x696)
PAIRS = [
 ("A_01_who-is-reading.png",                    "wait",      0, 0.46, 0.50, 1118, 3, (56, 272, 336, 696)),
 ("A_03_oral-first-What_sound_does_it_start.png", "point",    0, 0.46, 0.62, 1118, 4, (56, 292, 336, 696)),
 ("A_04_oral-blend-Which_word_do_the_sounds.png", "listen",   0, 0.62, 0.52, 1115, 5, (56, 292, 336, 696)),
 ("A_05_oral-count-How_many_sounds.png",         "try",       0, 0.66, 0.50, 1118, 8, (56, 292, 336, 696)),
 ("A_06_preview-Two_letters_for_next_tim.png",  "celebrate", 0, 0.50, 0.50, 1120, 7, (56, 272, 336, 696)),
]
def ours(shot, pose, y0, wfrac, cx, yb):
    bg = Image.open(f"{C}/round3/screens/{shot}").convert("RGBA").crop((0, y0, 780, y0 + 1125))
    k = to_alpha(f"{C}/tilo/pose_{pose}_raw.png"); w = int(780 * wfrac); k = k.resize((w, int(k.height * w / k.width)), Image.LANCZOS)
    bg.alpha_composite(k, (int(780 * cx - w / 2), yb - k.height))
    return bg.convert("RGB").resize((W, H), Image.LANCZOS)
def theirs(n, box):
    return Image.open(f"{C}/bar/duolingo_abc_{n}.jpg").convert("RGB").crop(box).resize((W, H), Image.LANCZOS)
def same(path, img):
    return ImageChops.difference(Image.open(path).convert("RGB"), img).getbbox() is None

rng = random.Random(20261010); key = {}
for i, (shot, pose, y0, wf, cx, yb, dn, box) in enumerate(PAIRS, 1):
    mine, other = ours(shot, pose, y0, wf, cx, yb), theirs(dn, box)
    sides = {"A": mine, "B": other} if rng.random() < 0.5 else {"A": other, "B": mine}
    for s, im in sides.items(): im.save(f"{O}/p{i}_{s}.png")
    # derive the key from what is on disk, then assert it
    found = [s for s in "AB" if same(f"{O}/p{i}_{s}.png", mine)]
    assert len(found) == 1, f"p{i}: could not identify ours uniquely on disk ({found})"
    ours_side = found[0]; other_side = "B" if ours_side == "A" else "A"
    assert same(f"{O}/p{i}_{other_side}.png", other), f"p{i}: the other side is not the Duolingo crop"
    assert not same(f"{O}/p{i}_{ours_side}.png", other)
    key[f"p{i}"] = {"ours": ours_side, "screen": shot, "tilo_pose": pose, "duolingo_shot": f"duolingo_abc_{dn}.jpg",
                    "file_ours": f"p{i}_{ours_side}.png", "sha1_ours": hashlib.sha1(open(f"{O}/p{i}_{ours_side}.png", "rb").read()).hexdigest()[:10]}
assert len({v["screen"] for v in key.values()}) == 5 and len({v["duolingo_shot"] for v in key.values()}) == 5
json.dump(key, open(f"{C}/round3_key.json", "w"), indent=1)
open(f"{C}/round3_key.js", "w").write("const KEY=" + json.dumps(key) + ";")
for k, v in key.items(): print(k, "ours =", v["ours"], v["screen"], v["tilo_pose"], "vs", v["duolingo_shot"])
