"""Curated picturable word concepts for Sound Out (L1-L4). slug -> (kind, what to draw).
kind: n noun, v verb/action, a adjective/state, f function word (best-effort scene, flagged ambiguous).
The description is what the picture shows; the STYLE prompt adds the look."""
W = {}
def n(**k):
    for s, d in k.items(): W[s.replace('_', ' ') if False else s] = ('n', d)
def v(**k):
    for s, d in k.items(): W[s] = ('v', d)
def a(**k):
    for s, d in k.items(): W[s] = ('a', d)
def f(**k):
    for s, d in k.items(): W[s] = ('f', d)

n(apple="one big shiny red apple with a green leaf", arm="a child's arm raised, hand open, shown from shoulder to fingertips", baby="a smiling baby sitting, wearing a pale yellow onesie",
  backpack="a small teal school backpack with two straps", bacon="three wavy pink-and-cream strips of bacon", bag="a plain brown paper shopping bag", ball="one round striped red-and-yellow beach ball",
  barn="a red farm barn with a white-trimmed big door and a hay-loft window", basket="a woven wicker basket with a curved handle", bat="a cute brown flying bat with open wings, hanging in the air", bath="a child sitting in a bathtub full of soap bubbles",
  bathtub="an empty white bathtub on little feet", beach="a sandy beach with blue sea and a small sandcastle", bear="a friendly brown bear sitting up", bed="a single bed seen from the side, flat, with a blue blanket and one plain cream pillow, nothing else", bell="one golden hand bell with a small clapper",
  belt="a brown leather belt with a gold buckle, coiled", bike="a child's bicycle in red with two wheels", bird="one small blue bird perched on a branch", boat="a small red boat floating on blue water", bone="one white dog bone",
  book="one closed hardcover book in blue with a plain cover", boot="one yellow rain boot", bottle="a clear plastic water bottle with a blue cap", box="a plain cardboard box with closed flaps", boy="a smiling boy with short dark hair in a green t-shirt standing",
  bread="a loaf of crusty bread with a slice cut", bridge="a small curved wooden bridge over a stream", bubble="three floating round soap bubbles with rainbow shine", bug="one cute red ladybird bug with black spots", bun="one round golden bread bun",
  bus="a yellow school bus seen from the side, plain, no writing", cabin="a small log cabin with a chimney and a door", cactus="a green cactus with two arms in a small pot", cage="a round golden bird cage with a small blue bird inside", cake="a birthday cake with pink icing and one candle",
  candle="one lit white candle with a small flame", cap="a blue baseball cap, plain, no logo", car="a small friendly blue car seen from the side", card="a plain folded greeting card with a heart on the front", cart="a wooden hand cart with two wheels filled with apples",
  cat="a cute orange tabby cat sitting", catfish="a grey catfish with long whiskers swimming", cave="a dark rocky cave opening in a hillside", chain="a short silver metal chain hanging in a loop", chair="a simple wooden chair", chef="a smiling chef with a tall white hat holding a spoon",
  chin="a smiling child's face with a finger softly touching the chin", circle="a big flat teal circle shape", city="a skyline of colourful tall buildings with windows", clay="a lump of brown clay on a table with a small clay pot being shaped", claw="a crab's big orange claw", cloud="one fluffy white cloud in a blue sky",
  clown="a friendly clown with a red round nose and colourful hair", coat="a warm red winter coat with buttons", coin="one shiny gold round coin", comb="a plastic blue comb", cook="a person cooking at a stove, stirring a pot", cop="a friendly police officer in a blue uniform and cap, waving",
  corn="a yellow ear of corn with green leaves", cot="a small baby cot bed with white bars and a baby blanket", cow="a black-and-white cow standing on grass", crab="a red crab with two big claws", crown="a golden crown with three round jewels", crumb="a tiny bread crumb on a plate, big and clear",
  cup="a white cup with a handle and a little steam", deer="a gentle brown deer with small antlers", den="a cosy fox den: a round hole in a hill with a small fox peeking out", desk="a wooden school desk with a pencil on top", dish="a round white plate with a spoon and fork beside it",
  dock="a wooden dock pier reaching into blue water with a rope post", dog="a cute brown-and-white puppy dog sitting with its tongue out", doll="a smiling soft rag doll with yarn hair and a blue dress", dolphin="a grey dolphin leaping over a wave", dot="one big round red dot on white",
  drum="a red drum with two drumsticks", duck="a yellow duck swimming on water", egg="one white egg", ear="a child's side face showing a big clear ear", eye="one big friendly eye with long lashes, brown iris", fan="an electric table fan with blue blades", farm="a small red farmhouse with a field and a fence",
  feather="one long soft blue feather", fern="a green fern plant with curling fronds", fig="a purple fig fruit cut open to show the pink inside next to a whole fig", fish="one orange fish swimming", flame="one orange-and-yellow campfire flame on logs", flute="a silver flute",
  fork="a silver fork", fox="a cute orange fox with a bushy tail sitting", frog="a green frog sitting on a lily pad", fruit="a bowl with an apple, banana and orange", garden="a flower garden with colourful flowers and a watering can", gate="a wooden garden gate, open", gem="one sparkling blue diamond-shaped gem",
  ghost="a cute friendly white ghost with a happy smile (not scary)", giant="a very tall friendly giant smiling, standing next to a tiny house", gift="a wrapped gift box with a red ribbon bow", girl="a smiling girl with two dark braids in a yellow dress standing", glue="a bottle of white glue with an orange cap",
  goat="a small white goat with little horns", grape="a bunch of purple grapes with a leaf", gum="a pink bubble being blown from a child's mouth", hair="a child with long curly brown hair, back view", ham="a pink slice of ham on a plate", hand="one open child's hand with five fingers", hat="a yellow sun hat with a ribbon",
  hawk="a brown hawk flying with wings spread", head="a smiling child's head and shoulders, plain", helmet="a red bike helmet", hen="a brown hen with a red comb standing", hill="a green grassy hill with one tree on top", hog="a pink hog pig, round and cute, standing", hole="a round hole in the ground with soil around it and a small shovel", home="a cosy small house with a smoking chimney and a door",
  hood="a child wearing a blue hooded raincoat with the hood up", hook="a big silver metal hook hanging", horn="a golden trumpet-shaped horn", horse="a brown horse standing with a white stripe on its face", hotdog="a hot dog in a bun with a yellow line of mustard", house="a simple house with a red roof, two windows and a door", hut="a small round thatched hut with a door",
  ice="three clear ice cubes", insect="a cute green grasshopper insect", jam="a glass jar of red jam with a spoon", jar="an empty glass jar with a lid beside it", jet="a white jet aeroplane flying in the sky", kid="a happy child jumping", king="a king with a golden crown and a red cape, smiling",
  kite="a diamond-shaped red kite flying in a blue sky with a long tail", kitten="a tiny fluffy grey kitten", knee="a child's bent knee with a round bandage on it", knot="a thick brown rope tied in a big knot", lamb="a fluffy white lamb", lawn="a green lawn with a lawn mower", leaf="one green leaf", leg="a child's leg with a shoe and sock",
  lid="a pot with its lid lifted, steam coming out", lip="a smiling child's face close up with pink lips", lock="a golden padlock closed", log="a brown wooden log with rings visible", map="a folded treasure map with a dotted path and an x mark", mask="a colourful party mask on a stick", mat="a round woven doormat on the floor", meat="a roast chicken drumstick on a plate",
  milk="a glass of white milk beside a milk carton", mitten="a pair of red knitted mittens", moon="a big yellow crescent moon with a star in a dark blue sky", moth="a soft brown moth with open wings", mouse="a small grey mouse with big round ears and a pink tail", mouth="a smiling child's face with the mouth big and open", muffin="a chocolate muffin in a paper cup",
  mug="a blue mug with a handle and steam", mule="a grey mule with long ears standing", napkin="a folded white cloth napkin on a plate", needle="a silver needle with a thread through its eye", nest="a bird nest with three blue eggs in a tree", net="a fishing net with a fish caught in it", nose="a smiling child's face with the nose big and round",
  nurse="a friendly nurse in a white-and-teal uniform with a stethoscope", nut="a brown walnut in its shell", owl="a brown owl with big round eyes on a branch", pan="a black frying pan with a fried egg", paw="a cat's paw with soft pink pads", pear="a green pear with a leaf", pen="a blue pen with the cap off", pie="a baked apple pie with a golden lattice top",
  pig="a cute pink pig standing", pin="a safety pin, silver", plane="a small propeller aeroplane flying", planet="a ringed orange planet in space with small stars", plate="a round white empty plate", pool="a swimming pool with blue water and a ladder", pot="a black cooking pot with a lid and steam",
  puppy="a tiny fluffy puppy with floppy ears", purse="a small red coin purse with a clasp", queen="a queen with a golden crown and a purple dress, smiling", rabbit="a white rabbit with long ears sitting", rainbow="a bright rainbow arching over green hills", rat="a small brown rat with a long tail", rice="a white bowl of steaming rice", ring="a gold ring with a blue stone",
  river="a blue river winding through green fields", road="a grey road with a yellow centre line going into the distance", robot="a cute small silver robot with round eyes and antennas", roof="the red tiled roof of a house with a chimney", room="a cosy room with a bed, a rug and a window", rope="a coiled yellow rope", rug="a round striped colourful rug on a wooden floor",
  sack="a brown burlap sack tied at the top", saddle="a brown horse saddle", sand="a pile of yellow sand with a small bucket and spade", shark="a grey shark swimming with its fin above water", shell="a pink spiral seashell on sand", ship="a big ship with sails on the sea", shirt="a blue shirt with buttons", shop="a small shop with an awning and fruits outside",
  shrimp="a pink shrimp curled up", skirt="a green skirt with a flowery pattern", sky="a blue sky with a big sun and a few white clouds", snail="a snail with a spiral brown shell", snake="a green snake coiled up, friendly smile", snow="a snowman in the snow with falling snowflakes", soap="a bar of pink soap with bubbles", sock="a pair of red-striped socks",
  spider="a small cute black spider on its web", squid="a red squid with long tentacles in blue water", star="one big yellow five-point star", stair="a wooden staircase with several steps", stove="a cooking stove with a pot on top and a small flame", straw="a drinking straw striped red-and-white in a glass of juice", string="a ball of red string with a loose end",
  sun="a big smiling-less bright yellow sun with short rays in a blue sky", table="a round wooden table with four legs", tail="a fox's bushy orange tail", tank="a clear glass fish tank with two small fish", tent="a blue camping tent with an open door under a tree", thumb="a child's hand with the thumb up", tiger="a cute orange tiger with black stripes sitting",
  toe="a bare foot with five toes, one toe wiggling", tool="a hammer and a wrench side by side", top="a colourful wooden spinning top toy", toy="a wooden toy train and a teddy bear", train="a red steam train on tracks", tray="a tray with a cup and a plate", tree="one big green tree with a brown trunk", tub="a round plastic tub full of water", tube="a squeezed tube of toothpaste with a toothbrush",
  van="a white delivery van, plain, no writing", wagon="a red wagon with a long handle holding a toy", wall="a red brick wall", web="a spider web with dew drops", whale="a big blue whale spouting water", wig="a curly rainbow-coloured clown wig", wing="one big white bird wing with feathers", worm="a pink earthworm on soil", wrench="a silver wrench",
  yak="a big black yak with long hair and horns", yard="a backyard with a green lawn, a fence and a swing", yarn="a ball of blue yarn with two knitting needles", zoo="a zoo scene with a giraffe and an elephant behind a fence", sun_cap="")  # sun_cap is removed below
W.pop('sun_cap', None)
W['sun'] = ('n', "a big bright yellow sun with short rays in a blue sky")

v(run="a child running fast with arms pumping, a small speed puff behind", jump="a child jumping high with both arms up", hop="a bunny hopping in the air", sit="a child sitting on a chair with feet on the floor", sat="a child sitting on a chair with feet on the floor", sleep="a child sleeping in bed with eyes closed and a small z-z mark",
  swim="a child swimming in a pool with arms stretched", clap="a child clapping hands with a happy smile and small motion lines", climb="a child climbing up a tree trunk", cry="a child crying with eyes squeezed and big tears streaming down", crying="a child crying with eyes squeezed and big tears streaming down", draw="a child drawing a picture on paper with a crayon",
  dig="a child digging a hole in the ground with a spade", eat="a child eating a sandwich with a happy face", drink="a child drinking from a glass of water", fly="a bird flying with spread wings in the sky", hug="two children hugging each other warmly", kiss="a mother giving her baby a kiss on the cheek", laugh="a child laughing with mouth wide open and eyes shut",
  read="a child reading an open picture book", write="a child writing with a pencil on paper, hand visible", sing="a child singing with mouth open and small music notes floating", kick="a child kicking a ball with one leg lifted", wave="a child waving hello with one hand raised", walk="a child walking along a path with a backpack", push="a child pushing a big box", pull="a child pulling a toy wagon on a rope",
  open="an open door with light coming out", cooking="a person stirring a pot on a stove", hide="a child hiding behind a tree with eyes peeking out", catch="a child catching a ball with both hands", ride="a child riding a bike", skate="a child ice skating on a rink", swing="a child on a swing in the air", wash="a child washing hands with soap bubbles", yawn="a child yawning with a wide open mouth and a hand over it",
  fix="a person fixing a toy with a screwdriver", jog="a person jogging in the park", nap="a cat napping curled up on a cushion", sip="a child sipping juice through a straw", snore="a sleeping bear with a big z-z-z", point="a child pointing a finger at a star", shake="two hands shaking", smile="a child with a big smile", dance="a child dancing with arms up", brush="a child brushing teeth with a toothbrush",
  hold="a child holding a teddy bear", pour="a hand pouring water from a jug into a glass", throw="a child throwing a ball with an arm back", wait="a child sitting on a bench looking at a clock", count="a child counting on fingers with five fingers held up", paint="a child painting with a brush at an easel", cut="a child cutting paper with scissors", pick="a child picking an apple from a tree", listen="a child cupping a hand behind an ear", look="a child looking through a magnifying glass",
  tie="a child tying a shoelace", brush2="")
W.pop('brush2', None)

a(big="a big elephant next to a tiny mouse", small="a tiny mouse next to a large cheese", tall="a very tall giraffe", hot="a bright sun and a child sweating wiping forehead, melting ice cream", cold="a child in a hat and scarf shivering in snow", wet="a child with an umbrella standing in heavy rain, wet puddles", dry="a sunny dry desert with a cactus",
  happy="a child with a big happy smile and cheeks pink", sad="a child with drooping shoulders and head tilted down, downturned mouth, arms hanging limp, no tears", mad="a child with an angry frown, puffed cheeks, arms crossed", sick="a child in bed with a thermometer and a sad pale face", full="a full glass of water to the brim", empty="an empty glass with nothing in it", fast="a cheetah running fast with speed lines", slow="a snail slowly crawling",
  dirty="a muddy child with mud spots on face", clean="a shiny clean child just washed with sparkles", sleepy="a child with half-closed eyes yawning, holding a teddy", scared="a child with wide eyes holding a blanket up near its mouth", shy="a child hiding half behind a parent's leg", silly="a child making a silly face with tongue out", heavy="a child struggling to lift a big heavy rock", long="a very long snake stretching across", thin="a very thin tall pencil",
  loud="a child covering ears next to a loud drum", soft="a fluffy soft kitten", hard="a grey hard rock", fat="a round chubby pig", thick="a very thick big book", old="an old grandfather with white hair and a cane", new="a shiny new red bike with a bow on it", red="one big red circle", blue="one big blue circle", green="one big green circle", yellow="one big yellow circle", pink="one big pink circle", black="one big black circle", white="one big white circle", brown="one big brown circle", gray="one big grey circle", purple="one big purple circle", orange="one big orange circle",
  busy="a child juggling many toys", proud="a child standing tall holding a gold medal", brave="a child standing tall facing a big shadow with a firm face", kind="a child sharing a cookie with a friend")
f(on="a ball on top of a box", **{"at": "a girl pointing at a star", "it": "a hand pointing at one apple on a table", "up": "a child reaching up high to a floating balloon"})

n(bee="a fuzzy yellow-and-black bee flying", bowl="a blue bowl full of soup with a spoon", branch="one brown tree branch with three green leaves", bucket="a blue bucket with a handle", bush="a round green bush with a few red berries", button="a big round red button with four holes",
  camel="a sandy camel with one hump standing", clock="a round wall clock with a white face and two hands showing three o'clock", computer="a laptop computer open with a plain blue screen", doctor="a smiling doctor in a white coat with a stethoscope around the neck", door="a closed wooden door with a round handle",
  drawer="a wooden chest of drawers with one drawer pulled open", engine="a blue car engine block with pipes", fence="a short white picket fence", field="a wide green field with a yellow wheat patch", foot="a bare foot seen from the side, big and clear", glove="a pair of green gardening gloves",
  grass="a patch of tall green grass with a small flower", hamster="a tiny golden hamster eating a seed", hedgehog="a cute brown hedgehog with spiky back", key="one golden key with a round head", kitchen="a kitchen with a stove, a table and a pot", lake="a round blue lake with two ducks and tall green trees behind",
  letter="a white envelope with a red heart seal, sealed", magnet="a red horseshoe magnet with silver tips attracting two nails", mother="a smiling mother with a bun hairstyle holding a small child's hand", notebook="a closed spiral notebook in orange", pencil="a yellow pencil with a pink eraser", phone="a mobile phone with a plain screen",
  pigeon="a grey pigeon walking", pillow="a soft white pillow", puzzle="a jigsaw puzzle with one piece lifted out", radio="an old radio with two knobs and an antenna", school="a school building with a bell tower and a door and a yard", shelf="a wooden wall shelf with books and a plant", stone="a smooth grey stone", storm="a dark grey storm cloud with rain and a yellow lightning bolt",
  street="a street with houses on both sides and a tree", teacher="a smiling teacher standing beside a board with a pointer, plain board no writing", umbrella="an open red umbrella", watch="a wrist watch with a round white face and blue strap", wheel="a big black wheel with silver spokes", wind="a tree bending with leaves blowing and swirly wind lines", window="a window with blue curtains and a view of the sky",
  pond="a small round pond with a frog on a lily pad", truck="an old blue pickup truck seen from the side", bin="a green rubbish bin with a lid", rain="grey clouds with rain falling and a child's yellow umbrella", stick="one brown wooden stick", shed="a small wooden garden shed", wood="a stack of cut firewood logs", park="a park with a bench, a tree and a path",
  farmer="a smiling farmer in a straw hat and overalls holding a basket of vegetables", friend="two children smiling side by side with arms around each other", sister="two girls, one taller one smaller, smiling side by side", family="a family of four standing together: two adults and two children", uncle="a smiling man with a moustache giving a thumbs up", grandpa="a smiling grandfather with white hair and glasses",
  grandmother="a smiling grandmother with grey hair in a bun and glasses", animal="a cow, a sheep and a chicken together", boss="a smiling man in a shirt and tie holding a clipboard", caravan="three camels walking in a line across sand", chest="a wooden treasure chest, open, with gold coins", cheese="a wedge of yellow cheese with holes", juice="a glass of orange juice with a straw", lunch="a lunch box open with a sandwich, an apple and a juice box")
