"""Round-2 prompt fixes from the haiku critic pass (word concept -> better 'draw'). Scenes take the critic's fix text from content/picture_scene_fixes.json."""
O = dict(
arm="a bare child's arm held straight out sideways from the shoulder with a relaxed open hand, short sleeve at the top, nothing else",
boat="a small wooden rowboat with a little sail floating on soft rounded blue waves, side view",
bun="a single golden-brown round bread roll with a split top, plain",
card="a greeting card standing open like a little tent, a big pink heart on the front",
cart="an empty wooden handcart with two handles and one big wheel, side view, no fruit",
catfish="a chubby grey catfish with four thick clearly visible whiskers around the mouth, side view",
clay="a lump of grey-brown soft clay on a wooden board with two hands pressing it",
claw="one big orange crab claw with an open pincer on a jointed arm",
coin="one round gold coin seen face-on with a simple star in the middle, no face",
cot="a baby cot seen from the side with a solid mattress, a sleeping baby inside, wooden rails",
crumb="three tiny bread crumbs scattered on a table, clearly small",
cup="an upright round white cup with one handle on the right, side view, a little steam",
den="an animal burrow: a round dark hole in a grassy bank with a small fox peeking out of it",
desk="a school desk with a sloped lid and a small seat attached",
dish="a deep serving dish of rice and curry with a spoon",
dock="a wooden jetty reaching into water with a small rowboat tied to a post at its end",
dot="one small red dot, as small as a button, in the middle of a big empty white space",
ear="a single large human ear, side view, with a little hair above it, no face",
farm="a red barn with a cow and a tractor in front of a green field with crop rows",
fern="one big green fern frond with many small leaflets, no pot",
fig="one whole purple fig and one fig cut in half showing the red seeds inside, green stem",
flame="one big orange-and-yellow flame shape alone, no logs, no candle",
flute="a silver flute with a row of round keys, soft and cute",
gate="a wooden garden gate swung open on its hinges with a latch, fence posts at each side",
gem="one sparkling red ruby gem, faceted",
giant="a very tall friendly giant standing next to a small house and a tiny person, the giant's head higher than the roof",
glue="a white glue bottle with an orange cap squeezing out a drip of white glue",
goat="a brown goat with a small beard and curved horns standing",
gum="one stick of pink chewing gum with a half-open silver wrapper",
hair="a child's long wavy brown hair hanging down, back of the head, being brushed with a hairbrush",
ham="a whole cooked ham joint on a platter with shiny glaze",
hand="one open hand with five spread fingers, palm facing us, no face on it",
hawk="a hawk perched on a branch with a sharp hooked beak and fierce-friendly eyes",
head="a smiling child's head only, front view, whole head and a little neck inside the frame",
hen="a brown hen sitting on straw with a red comb",
hill="a green grassy hill with small flowers on the slope, no tree",
hood="a blue raincoat hood pulled up over a child's head, child seen from the front, the hood big and clear",
horn="a curved brass horn with a wide bell",
house="a plain red-roof house with two windows and a door, no face",
insect="a green beetle seen from above with six legs and two antennae",
jet="a grey fighter jet with swept wings flying",
kite="a red diamond kite with a long tail and bows, only the kite on white, no sky",
knee="a child's bent leg showing thigh, knee and shin, with a round bandage on the knee",
knot="a thick brown rope tied in a big knot with two loose ends",
lamb="a tiny white lamb with short wobbly legs and a tiny tail",
leg="a whole bare child's leg from hip to foot wearing a sock and a shoe, fully in frame",
lid="one round silver pot lid with a handle on top, alone",
lip="a close-up of pink smiling lips only, no other face parts",
log="a cut tree log lying on its side, bark visible and growth rings at the end",
mat="a rectangular woven doormat with fringe, flat, straight edges",
meat="a raw red steak on a wooden board",
moth="a fuzzy brown moth with feathery antennae resting with wings flat",
mouth="a close-up of a wide open smiling mouth with teeth and tongue, no eyes",
muffin="a golden muffin with a cracked crumbly top in a brown paper liner, no frosting",
mule="a brown mule with a saddle blanket and long ears",
napkin="a neatly folded white cloth napkin, alone",
nest="a bird's nest alone, woven twigs with three blue eggs, no tree",
net="an empty fishing net with a mesh pattern on a wooden handle, no fish",
nose="a close-up of a child's round nose with two nostrils, no eyes",
nut="one whole walnut in its shell, no face",
paw="a cat paw print: four round toe pads and one big pad, brown, no face",
pen="a blue ballpoint pen with a clip, blunt tip, cap on",
plate="a round white dinner plate with a fork on the left and a knife on the right",
queen="an adult queen with a tall gold crown and a long purple robe holding a sceptre",
rabbit="a white rabbit with long upright ears, smooth flat fill",
rat="a brown rat with a long thin tail and pointed snout",
rice="a bowl of cooked rice with a spoon, clearly separate grains",
river="a river seen from the side with grassy banks, a few rocks and a small wooden bridge",
room="a whole room: walls, floor, a window, a door, a small rug and a lamp",
rug="a rectangular red rug with fringe tassels on a wooden floor",
saddle="a brown leather horse saddle with stirrups sitting on the back of a brown horse",
sand="a flat yellow sand patch with soft ripples, no bucket",
shark="a grey shark with a tall triangular fin and torpedo-shaped body, friendly smile",
shell="a fan-shaped scallop seashell with ridges",
sky="a few fluffy white clouds on a soft blue rounded tile, no sun",
snake="a green snake stretched in an S-curve with a little forked tongue",
snow="snowy ground with big falling snowflakes and a small pile of snow, no snowman",
soap="a cream rectangular soap bar with rounded edges and a few bubbles",
squid="a squid with a torpedo-shaped body, two triangle fins and ten tentacles",
straw="a single red-and-white striped drinking straw with a bend, alone",
string="a single loose piece of thin string lying in a curve",
sun="a yellow sun with short rays, alone, no sky",
tank="a rectangular glass fish tank with water, a lid, two fish and a plant",
tent="a blue camping tent with an open door flap, filling the frame, no tree",
toe="a close-up of a foot with the big toe lifted and large",
tool="a hammer alone, centred",
toy="a wooden rocking horse toy",
tube="a toothpaste tube with its cap off, squeezed, with a little paste at the end",
wagon="an empty red wagon with four wheels and a pull handle, no toys",
wig="a rainbow-coloured curly wig on a wig stand",
yak="a black yak with long shaggy fur down to the ground, curved horns and a hump",
hop="a child mid-hop on one foot with the other foot lifted, arms out, small bounce marks",
cry="a small child crying with mouth open and tears streaming down",
kiss="a mother's lips kissing a baby's cheek, lips touching the cheek",
open="a hand pushing a door half open with light coming through",
catch="a child with both arms out catching a ball that has just arrived in the hands, joyful",
fix="a child tightening a bolt on a bicycle wheel with a spanner",
nap="a child asleep on a sofa with a blanket and small pillow",
sip="a child's lips sipping through a straw from a small cup",
snore="a sleeping child with mouth open and a small bubble from the nose",
hold="a child holding a cup out in one hand",
wait="a child standing with hands clasped looking at a closed door",
count="a child showing three fingers on one hand",
pick="a hand plucking one big apple from a branch",
look="a child with a hand shading the eyes looking far away",
tie="two hands pulling a shoelace into a bow, close-up",
small="a tiny mouse next to one crumb, nothing else",
tall="a child standing on tiptoes reaching up high",
wet="a child dripping wet standing in a puddle, wet hair, no umbrella",
dry="dry cracked mud ground with deep cracks",
full="a cup filled to the brim with water touching the rim",
empty="a cup lying on its side with nothing inside",
slow="a turtle walking slowly",
shy="a child peeking shyly from behind a door",
long="a very long ribbon stretched across the whole frame",
soft="a hand pressing into a soft fluffy pillow",
thick="a thick book next to a thin book",
old="a worn old shoe next to a shiny new shoe",
white="one white fluffy cloud",
bowl="an empty round bowl, open at the top, no food",
key="a classic gold key with a round bow and teeth at the end",
puzzle="a few jigsaw puzzle pieces with one piece lifted, fully in frame",
street="a road with lane lines and a pavement running across the frame",
wind="a windsock blowing stiff sideways with swirly wind lines",
pond="a round pond with lily pads, reeds and ripples, no frog",
rain="a grey rain cloud with heavy rain drops falling and a puddle below",
shed="a garden shed with a sloped roof and a rake leaning on the wall",
wood="a pile of wooden planks",
farmer="an adult farmer in a straw hat and overalls holding a rake",
sister="two girls of similar height in matching dresses holding hands",
caravan="a camel pulling a covered wagon",
)

# round 3 (after the second haiku pass)
O.update(
cup="an upright blue cup with one handle and a little steam, side view",
hill="a big smooth green mound hill with a winding path up it and small flowers, no bush",
knee="a child sitting with legs folded, one bent knee big in the foreground with a round bandage on it",
leg="a child's bare leg, hip to foot with a sock and shoe, drawn small and centred with wide margin",
lid="a pot with its lid floating just above it, the lid with a round knob",
mouth="a close-up of a smiling closed-lip mouth with a pink tongue peeking out, cute, no eyes",
napkin="a folded teal cloth napkin alone",
nut="two peanuts in their shells",
plate="a big round blue plate with a rim, alone, no cutlery",
queen="an adult woman queen with long hair, a jewelled gold crown with no cross, a long purple gown, holding a sceptre",
rabbit="a pale grey-brown rabbit with long upright ears",
river="a wide blue river flowing between green banks, no bridge",
saddle="just a brown leather horse saddle with a girth strap and stirrups, no horse",
sand="a hand pouring fine golden sand into a little pile",
snow="a small pile of snow with big falling snowflakes drawn in light blue and grey shading",
string="a thin tan string lying in a loose curl with both ends visible",
toe="a close-up of one big toe pointing up with a toenail, large",
catch="a ball flying in the air above a child's stretched-up hands, about to be caught",
fix="a child holding a wrench next to a broken toy robot",
hold="two hands holding a small teddy bear up",
count="a child holding up three fingers, each finger clearly separate, hand large",
pick="a hand plucking one big apple from a branch, drawn small with wide margin",
empty="a cup seen from above showing an empty inside",
white="one white fluffy cloud on a pale blue round tile",
puzzle="a few jigsaw puzzle pieces with one piece lifted, drawn small with wide margin",
street="a street with houses on both sides, a road with a small car and a pavement",
shed="a wooden shed with a wide double door, a rake and a wheelbarrow beside it, no windows",
cart="a wooden market cart with two big wheels, a flat bed and two handles, empty",
bun="a plain round golden bread roll with a smooth top, no scoring",
giant="a huge giant walking beside tiny trees and a small house at his ankle",
)
S = {
"scene:L1.03:0": "A red race car turns off the main track into a side lane while two other race cars continue side by side on the main track, a few cheering people in the stands",
"scene:L1.04:1": "Close view of Mr. Iqbal, an older man with a white moustache and brown vest, with big worried eyebrows raised in the middle and a worried frown, in front of his small shop with empty shelves behind him",
"scene:L1.04:4": "Mr. Iqbal, white moustache and brown vest, pedals an old bicycle carrying a long black bicycle pump clearly sticking out of the front basket, smiling with effort",
"scene:L1.11:0": "A friendly vet in a white coat with a stethoscope checking a golden dog; one single scene only",
"scene:L1.13:0": "A busy warehouse worker with a frown holds a shipping box and studies it carefully; one big delivery truck beside him clearly pointing the wrong way",
"scene:L1.14:0": "A girl at a desk with a big blank test paper, a thoughtful focused face with a small smile, pencil in hand",
"scene:L2.02:1": "Pip the orange cat with white paws leans forward and gently taps a curled sleeping hedgehog with one paw, the hedgehog's spines up in surprise",
"scene:L2.08:1": "Bruno, a shaggy brown dog (clearly a dog), sits shyly far on the right looking away, while a girl smiles at him from the left",
"scene:L2.11:2": "Ayesha, a girl of twelve with long black hair, walks into a bright classroom from the right with a pencil in her hand, the whole room inside the frame with a few desks",
"scene:L2.12:1": "A rebuilt wooden market stall in warm orange wood, a hammer lying on the counter and a small coin purse beside it, a happy stall owner standing behind",
}

# round 4: colours as paint splashes, plus three the final critic flagged
for _c in "red blue green pink black white brown gray purple".split():
    O[_c] = f"one big flat splash of pure {_c} paint with a soft rounded blobby shape, and a small paintbrush resting beside it"
O["white"] = "one big flat splash of white paint on a pale grey-blue round tile, with a small paintbrush beside it"
O["saddle"] = "a horse seen from the side wearing a brown leather saddle with stirrups and a blanket, the saddle large and clear"
O["count"] = "a child holding up one hand with three fingers clearly raised and separate, fingers big"
O["crumb"] = "a thick slice of bread with three small crumbs falling beside it, crumbs large"

# round 5 (blind critic fails, plan/picture-qa.md)
O.update(
brush="one large flat paint brush alone, wooden handle and bristles loaded with orange paint, no child, no toothbrush",
bug="a cute green-brown beetle seen from above with a plain shiny shell, six legs and two antennae, no spots, not a ladybird",
bun="one round bread bun with sesame seeds on top, plain, alone",
claw="one cat paw seen from the front with five sharp curved white claws sticking out of the toe pads, no face",
cot="an empty folding camp cot: green canvas stretched on a wooden frame with four crossed legs, side view, no baby, no pillow",
den="an empty animal burrow: a big round dark hole in a grassy mound, nothing inside, no animal",
dish="an empty white oval serving dish with two handles, with a fork and a spoon beside it, no food",
dry="a fluffy yellow dry towel hanging on a rail under a smiling bright sun",
empty="an empty clear drinking glass in side view, nothing inside",
fast="a red sports car speeding sideways with long horizontal speed lines streaming behind it",
flute="a wooden recorder flute with a mouthpiece and a row of dark finger holes, shown diagonally, clearly a musical instrument",
fly="a cute bumblebee flying with blurred round wings and a dotted curved flight path behind it",
full="a tall clear glass filled to the brim with orange juice, one drop spilling over the rim",
giant="a gigantic friendly man whose head is three times higher than a tiny cottage, standing behind the cottage",
hawk="a brown hawk perched on a branch, hooked yellow beak, sharp yellow eyes, streaked cream chest, strong talons, clearly a bird of prey and not an owl",
hop="a bunny hopping through the air in a small arc with feet off the ground and a dotted arc trail",
knee="a close-up of a child's bent knee only, with a scraped red patch and a plaster, the knee fills the frame, no face",
lawn="a neatly mown green striped lawn with a red push lawnmower on it",
long="a very long brown rope lying in a gentle S curve from the left margin to the right margin",
moth="a fuzzy beige-grey moth with wide feathery comb-like antennae, a furry chubby body and dull brown patterned wings folded flat",
napkin="a white paper napkin folded in a triangle lying on a table beside a plate and a fork",
nut="one walnut shell split half open showing the wrinkly brain-shaped kernel inside",
point="a child's arm with the hand's index finger stretched out pointing at a red apple on the right",
ride="a child sitting on a brown horse holding the reins, side view, riding along",
room="a cosy room shown front-on with four walls and a floor, a sofa, a floor lamp and a window",
sip="a child tipping a small cup to the lips taking a tiny sip, eyes closed, no straw",
small="one tiny green pea beside a huge orange pumpkin, big contrast in size",
snore="a child asleep on their back in bed with mouth wide open, a snot bubble at the nose and wavy sound lines from the mouth",
snow="a round snowman with a carrot nose on a small mound of white snow with falling snowflakes",
straw="a red-and-white striped bendy drinking straw standing in a glass of orange juice",
tail="a whole orange fox sitting side-on with its big bushy white-tipped tail curled behind it",
tall="a tall giraffe standing next to a small child, both fully in frame",
thumb="a close-up of a fist with the big thumb stretched out sideways, the thumb large and the other four fingers curled, no face",
tie="a blue necktie knotted at the collar of a white shirt, front view, shirt torso only, no head",
tube="a yellow squeezable cream tube with a red screw cap, flat crimped end, standing on its cap, no paste coming out",
wait="a child sitting on a bench looking up at a big round wall clock with only tick marks and no numbers, chin on hand, foot tapping",
wig="a curly orange wig sitting on a plain faceless mannequin head",
wind="three autumn leaves and a red kite blowing sideways with curved wind lines streaming past",
)

# round 5 second attempts (concrete nouns that still read wrong)
O.update(
claw="a yellow eagle foot with three long sharp curved black claws gripping a branch, no body",
napkin="a white paper napkin folded in a triangle standing upright like a little tent beside a fork, no table, no plate",
thumb="an open child's hand seen from the back with the thumb sticking out to the side and a bright yellow circle drawn around only the thumb",
)

# round 6 (independent critic round 2)
O.update(
claw="one big orange crab claw with a wide open pincer, isolated, large, no body and no branch",
cot="a baby cot with tall vertical wooden bars on all sides, a small blue blanket inside, side view, no baby",
den="a fox den: a round dark hole in a grassy bank with a small orange fox peeking its head out of the hole",
fly="a housefly seen from above: grey body, two big red compound eyes, two transparent wings, no stripes, six thin legs",
hawk="a hawk seen side-on in flight with both wings spread wide, hooked beak, sharp eyes, brown streaked body, long tail",
knee="a child's bent leg seen from the side with a bright yellow circle drawn around the knee, no plaster, no bandage",
moth="a brown fuzzy moth with feathery antennae resting beside a glowing street lamp at night, dark navy night background tile",
napkin="a folded white cloth napkin lying on a table beside a round plate with a fork",
tail="a happy dog seen from behind-side with its tail raised and wagging, the tail large and emphasised with small motion lines",
wind="a tree bending sideways in a strong wind with big swirly wind lines and leaves blowing off it",
)
O.update(
knee="a close-up of a bare bent knee, the kneecap bulging at the centre of the frame, thigh above and shin below, with a bright yellow circle drawn exactly around the kneecap, no plaster, no shoes",
napkin="a white cloth napkin folded into a neat rectangle with a blue stripe along the edge, lying flat on a pale wooden table placed on the left of a round plate, whole napkin fully inside the frame with margin",
tail="a pink pig seen from the side with a small tightly curly corkscrew tail on its rump, the curly tail large and clear",
)
